# biofirst.co now redirects to the public brand domain
server {
    server_name biofirst.co www.biofirst.co biofirst.fit www.biofirst.fit biofirst.shop www.biofirst.shop;
    listen 443 ssl;
    listen [::]:443 ssl;
    ssl_certificate /etc/letsencrypt/live/biofirst.co/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/biofirst.co/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    return 301 https://biolabsresearch.co$request_uri;
}
server {
    listen 80;
    listen [::]:80;
    server_name biofirst.co www.biofirst.co biofirst.fit www.biofirst.fit biofirst.shop www.biofirst.shop;
    return 301 https://biolabsresearch.co$request_uri;
}
